### ISSUE TITLE
Importar el repositorio de meshtastic-device 

### ISSUE THREAD

**Issue by dberasategui** [MartinNievas/Red-de-comunicaciones-para-emergencias#23]
Para meterlo en /MeshtasticVersion. 
Hay que ver cómo se importa de manera correcta

**Comment by MartinNievas** [comment]
Hola, estuve analizando el repo ya haciendo unas pruebas en un [fork](https://github.com/MartinNievas/Meshtastic-device) (todavía no las subí). Al parecer hay dos opciones:
- Utilizar Meshtastic mediante las [API](https://meshtastic.org/docs/developers/device/device-api),
- Crear [Plugins](https://meshtastic.org/docs/software/plugins/plugins). La API no llegué a realizar pruebas.

Para el caso de la segunda, logré configurar platformio (que es la herramienta que al fin se encarga de compilar y linkear) para tomar un plugin externo como [este](https://github.com/meshtastic/Meshtastic-device/blob/master/src/plugins/ReplyPlugin.cpp). No llegué a realizar pruebas con la API.

No se si ya la utilizaron a la biblioteca anteriormente, pero parece que mediante los plugins puede funcionar

Edit: Recién subí los cambios a una rama separada, acá está el [commit](https://github.com/MartinNievas/Meshtastic-device/commit/6f8b2b66381faf884ab5bba1d97631983cf38626) con los cambios para utilizar un archivo externo como plugin

**Comment by dberasategui** [comment]
Se creó el submódulo meshtastic-device en /devel, desde el fork MartinNievas/Meshtastic-device.

![image](https://user-images.githubusercontent.com/37606743/129462860-f987dfe1-1e68-4d72-b574-db75dbbb2e68.png)
